services:
    ersatztv:
        build:
            context: ..
            dockerfile: docker/Dockerfile
            args:
                INFO_VERSION: "docker-compose-develop"
        environment:
            TZ: Europe/Amsterdam
            ETV_STREAMING_PORT: "8509"
            ETV_UI_PORT: "8510"
        ports:
            - "8509:8509"
            - "8510:8510"
        volumes:
            - ersatztv:/config
            #- /media/shared:/media/shared:ro
        tmpfs:
            - /transcode
volumes:
    ersatztv:
